### ISSUE TITLE
Uninterrupted receive loop (CPU 100%)

### ISSUE THREAD

**Issue by breml** [logstash-plugins/logstash-input-zeromq#17]
ZeroMQ input uses 100% CPU

Even without actual traffic, the zeromq input plugin produces 100% load. The reason is the ZMQ::DONTWAIT setting in https://github.com/logstash-plugins/logstash-input-zeromq/blob/master/lib/logstash/inputs/zeromq.rb#L132, introduced by https://github.com/logstash-plugins/logstash-input-zeromq/commit/cef68df3d53e9bcd335d377e317fc8f6acfcb350

The ZMQ::DONTWAIT setting (http://api.zeromq.org/3-0:zmq-recv) enables the non-blocking mode on the ZeroMQ socket. If no message is available, on the socket, the recv_string method returns ZMQ::EAGAINT and the next on line 133 is executed. This leads to an endless loop of lines 128 to 133 and therefore to 100% CPU usage (at least on one CPU core).

Steps to reproduce:

Start logstash with the following config and watch the CPU, for example with top

```
input {
  zeromq {
    topology => "pushpull"
  }
}
output {
  stdout {}
}
```

I suggest to change the implementation to use ZMQ::RCVTIMEO (for example with a value of 1000) instead of ZMQ::DONTWAIT.

**Comment by erikthorselius** [comment]
:+1:
